version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Zipping Lambda package..."
      - zip -r lambda-package.zip ./ -x buildspec.yml
      - echo "Build completed successfully."
  post_build:
    commands:
      - echo "Updating Lambda function code..."
      - aws lambda update-function-code --function-name 22ug1-0230_lambda_code_build_function --zip-file fileb://lambda-package.zip
      - echo "Waiting for the code update to complete..."
      - sleep 10
      - echo "Updating Lambda function configuration..."
      - aws lambda update-function-configuration --function-name 22ug1-0230_lambda_code_build_function --handler lambda.handler
artifacts:
  files:
    - lambda-package.zip
